# Generated by Django 5.2.9 on 2026-09-05 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_alter_checklist_options_alter_progress_hours_studied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='category',
            field=models.CharField(choices=[('개발', '개발'), ('디자인', '디자인'), ('언어', '언어'), ('비즈니스', '비즈니스'), ('기타', '기타')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='current_level',
            field=models.CharField(choices=[('입문', '입문'), ('초급', '초급'), ('중급', '중급'), ('고급', '고급')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='daily_hours',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='duration_weeks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
